site_name: My Site
site_url: https://skyraman.github.io/performance/
repo_url: https://github.com/skyraman/performance.git

nav:
    - Home: index.md
    - Achievements: docs/achievements.md
    - Skills: docs/skills.md
